version: 2

sources:
  - name: tpch
    schema: main
    tables:
      - name: customer
      - name: orders
      - name: lineitem
      - name: nation
      - name: region
      - name: supplier
      - name: part
      - name: partsupp